#!/usr/bin/env bash
export CUDA_VISIBLE_DEVICES=4,5,6,7
#
#python train.py @configs/train_deltar_change_embedding_no_clip_grad_hist_encoder_optimized_10x_cvxt27_2x2.txt
python evaluate_all.py @configs/train_deltar_change_embedding_no_clip_grad_hist_encoder_optimized_10x_cvxt27_2x2.txt
python evaluate_all.py @configs/train_deltar_change_embedding_no_clip_grad_hist_encoder_optimized_10x_cvxt27_2x2.txt --test_dataset nyu

#python train.py @configs/train_deltar_change_embedding_no_clip_grad_hist_encoder_optimized_10x_cvxt28_2x2.txt
python evaluate_all.py @configs/train_deltar_change_embedding_no_clip_grad_hist_encoder_optimized_10x_cvxt28_2x2.txt
python evaluate_all.py @configs/train_deltar_change_embedding_no_clip_grad_hist_encoder_optimized_10x_cvxt28_2x2.txt --test_dataset nyu

#
#

